[mappings]
"RACF-GENERIC-WARNING" = ["NIST-AC-2", "PCI-8.1"]
"DATASET-WEAK-PERMISSION" = ["NIST-AC-3", "CIS-1.2.3"]
"APF-WEAK-PERMISSION" = ["NIST-AC-6", "PCI-2.2"]
"JES-WEAK-CONFIG" = ["NIST-AU-6", "PCI-10.5"]
"UNIX-WEAK-PERMISSION" = ["NIST-AC-3", "CIS-2.1.4"]
"STC-WEAK-CONFIG" = ["NIST-AC-2", "PCI-8.5"]